#!/bin/bash
ISL_UTILS_LOC=${ISL_UTILS_ROOT}
POLYITE_LOC=${POLYITE_ROOT}
LD_PRELOAD=${ISL_UTILS_LOC}/lib/libisl.so.15.0.0 /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -XX:+UseG1GC -Djava.library.path=${ISL_UTILS_LOC}/lib -classpath ${POLYITE_LOC}/bin:${ISL_UTILS_LOC}/bin:${POLYITE_LOC}/lib/scala-library-2.11.jar:${ISL_UTILS_LOC}/lib/isl-scala.jar:${POLYITE_LOC}/lib/scala-parser-combinators_2.11-1.0.4.jar polyite.util.PrintSCoPSize "$1"
